version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      colordx:
        patterns:
          - '@colordx/*'
      svelte:
        patterns:
          - 'svelte'
          - '@sveltejs/*'
      biome:
        patterns:
          - '@biomejs/*'
      tooling:
        patterns:
          - 'vite'
          - 'typescript'
          - 'svelte-check'
          - '@types/node'
          - 'rollup-plugin-visualizer'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
