// This file is auto-generated by scripts/generate-manifest.mjs.
// Do not edit manually — changes will be overwritten.
// Run `bun run manifest` to regenerate.

export type SetManifestEntry = {
    id: string;
    title: string;
    file: string;
    useNameAsBg: boolean;
};

export const SET_MANIFEST: SetManifestEntry[] = [
    { id: 'bootstrapList', title: 'Bootstrap', file: 'bootstrap.json', useNameAsBg: false },
    {
        id: 'catppuccinFrappe',
        title: 'Catppuccin Frappé',
        file: 'catppuccin-frappe.json',
        useNameAsBg: false,
    },
    {
        id: 'catppuccinLatte',
        title: 'Catppuccin Latte',
        file: 'catppuccin-latte.json',
        useNameAsBg: false,
    },
    {
        id: 'catppuccinMacchiato',
        title: 'Catppuccin Macchiato',
        file: 'catppuccin-macchiato.json',
        useNameAsBg: false,
    },
    {
        id: 'catppuccinMocha',
        title: 'Catppuccin Mocha',
        file: 'catppuccin-mocha.json',
        useNameAsBg: false,
    },
    {
        id: 'colorList',
        title: 'CSS Named Colors',
        file: 'css-named-colors.json',
        useNameAsBg: true,
    },
    { id: 'draculaList', title: 'Dracula', file: 'dracula.json', useNameAsBg: false },
    { id: 'primerList', title: 'GitHub Primer', file: 'github-primer.json', useNameAsBg: false },
    { id: 'gruvboxList', title: 'Gruvbox', file: 'gruvbox.json', useNameAsBg: false },
    {
        id: 'materialList',
        title: 'Material Design',
        file: 'material-design.json',
        useNameAsBg: false,
    },
    { id: 'nordList', title: 'Nord', file: 'nord.json', useNameAsBg: false },
    { id: 'oneDarkList', title: 'One Dark', file: 'one-dark.json', useNameAsBg: false },
    { id: 'oneLightList', title: 'One Light', file: 'one-light.json', useNameAsBg: false },
    {
        id: 'pantone-uncoated',
        title: 'Pantone Uncoated',
        file: 'pantone-uncoated.json',
        useNameAsBg: false,
    },
    { id: 'pantone', title: 'Pantone Coated', file: 'pantone.json', useNameAsBg: false },
    { id: 'ral-classic', title: 'RAL Classic', file: 'ral-classic.json', useNameAsBg: false },
    {
        id: 'resistorColorList',
        title: 'Resistor Color Code',
        file: 'resistor-color-code.json',
        useNameAsBg: false,
    },
    { id: 'solarizedList', title: 'Solarized', file: 'solarized.json', useNameAsBg: false },
    { id: 'tableauColorList', title: 'Tableau 20', file: 'tableau-20.json', useNameAsBg: false },
    {
        id: 'tailwindColorList',
        title: 'Tailwind CSS v4',
        file: 'tailwind-v4.json',
        useNameAsBg: false,
    },
    { id: 'tokyoNightList', title: 'Tokyo Night', file: 'tokyo-night.json', useNameAsBg: false },
    {
        id: 'powershellColorList',
        title: 'Windows Terminal',
        file: 'windows-terminal.json',
        useNameAsBg: false,
    },
    { id: 'xtermColorList', title: 'xterm-256', file: 'xterm-256.json', useNameAsBg: false },
];
